/* Generated By:JavaCC: Do not edit this line. DartCompilerConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface DartCompilerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMA = 6;
  /** RegularExpression Id. */
  int COLON = 7;
  /** RegularExpression Id. */
  int SEMI_COLON = 8;
  /** RegularExpression Id. */
  int POINT = 9;
  /** RegularExpression Id. */
  int LP = 10;
  /** RegularExpression Id. */
  int RP = 11;
  /** RegularExpression Id. */
  int LC = 12;
  /** RegularExpression Id. */
  int RC = 13;
  /** RegularExpression Id. */
  int EQ = 14;
  /** RegularExpression Id. */
  int OP1 = 15;
  /** RegularExpression Id. */
  int OP2 = 16;
  /** RegularExpression Id. */
  int QOUTE = 17;
  /** RegularExpression Id. */
  int PRINT = 18;
  /** RegularExpression Id. */
  int DEC_INT = 19;
  /** RegularExpression Id. */
  int DEC_STRING = 20;
  /** RegularExpression Id. */
  int DEFINE = 21;
  /** RegularExpression Id. */
  int AS = 22;
  /** RegularExpression Id. */
  int LETTER = 23;
  /** RegularExpression Id. */
  int LOWERLETTER = 24;
  /** RegularExpression Id. */
  int UPPERLETTER = 25;
  /** RegularExpression Id. */
  int DIGIT = 26;
  /** RegularExpression Id. */
  int IDENTIFIER = 27;
  /** RegularExpression Id. */
  int CLASSNAME = 28;
  /** RegularExpression Id. */
  int NUM = 29;
  /** RegularExpression Id. */
  int STRING = 30;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "\",\"",
    "\":\"",
    "\";\"",
    "\".\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"=\"",
    "\"??\"",
    "\"??=\"",
    "\"\\\"\"",
    "\"print\"",
    "\"int\"",
    "\"string\"",
    "\"define\"",
    "\"as\"",
    "<LETTER>",
    "<LOWERLETTER>",
    "<UPPERLETTER>",
    "<DIGIT>",
    "<IDENTIFIER>",
    "<CLASSNAME>",
    "<NUM>",
    "<STRING>",
  };

}
